### ISSUE TITLE
Incorrect results with reduceByKey

### ISSUE THREAD

**Issue by tovbinm** [databricks/spark-avro#102]
Howdy,

We've noticed a strange behavior with Avro serialized data and reduceByKey RDD functionality. Please see below:
```scala
val data: RDD[T] = sparkContext.hadoopFile(path, classOf[AvroInputFormat[T]], classOf[AvroWrapper[T]], classOf[NullWritable]) // we're reading an avro serialized data
val bad: RDD[(String,List[T])]  = data.map(r => (r.id, List(r))).reduceByKey(_ ++ _) // incorrect data returned
val good: RDD[(String,List[T])] = data.map(r => (r.id, List(r))).partitionBy(Partitioner.defaultPartitioner(data)).reduceByKey(_ ++ _) // OK, as expected
```
Any ideas? 

Thanks in advance.

**Comment by marmbrus** [comment]
My best guess would be that you aren't coping somewhere and avro is reusing objects.  That said, you aren't actually using this library (spark-avro) which would hide such details from you.

**Comment by marmbrus** [comment]
I'm going to close this issue since this question isn't really about this library, but if you are having further problems I'd suggest asking on the spark-user list.
