### ISSUE TITLE
storage directory structure aware queries

### ISSUE THREAD

**Issue by Gauravshah** [databricks/spark-avro#103]
I am trying to read s3 directory using sparksql.

```
CREATE TEMPORARY TABLE events_spark
USING com.databricks.spark.avro
OPTIONS (path "s3://s3-basin/events_v2/")
;
```

The folder structure on s3 is `events_v2/year/month/date/hour/events.avro`. Is there any way to query the data like `select count(*) from events_spark where year=2015 AND month = 10 AND date = 12`

I am able to do the same if I have the following directory:
`events_v2/year=2015/month=11/day=20`

**Comment by JoshRosen** [comment]
This is a general question regarding data source partitioning and thus is better suited to the Spark mailing list rather than this specific data source's repository. Therefore, I'm going to close this issue.
