### ISSUE TITLE
DataFrame write avro custom name

### ISSUE THREAD

**Issue by hackercompany** [databricks/spark-avro#107]
I am writing a datafrme to avro like 

```
dfs.write.avro(out_path)
```

this adds a uuid at the end of each file

and the file that gets created has a name like 
part-r-00000-uuid.avro

Is there a way to remove the uuid or to altogether give a custom name to the export file ?

**Comment by vlyubin** [comment]
There currently isn't a way to do it, but you can change logic in `AvroOutputWriter` to get the desired behaviour. Though it might be easier to just rename the file after it was created.

**Comment by JoshRosen** [comment]
Yep, @vlyubin is right.
