### ISSUE TITLE
write/append to specific avro file

### ISSUE THREAD

**Issue by vamdir** [databricks/spark-avro#111]
Hi

Currently we have a way to write/append to an avro in an output location.  
dfs.write.mode("append").avro(out_path)
Currently the API doesn't allow us to specify a file name instead of directory in out_path . 
This behavior creates one file per executor for each run. This inturn results in lots of small files when the job runs multiple times in a day.

Is there any plan to implement the functionality to write/append to specific avro file in near future?
Do we have an alternate way to achieve this for now?

**Comment by JoshRosen** [comment]
This limitation is shared by other Spark data sources, including `csv` and `json`. Given this, I think this question is slightly out of scope here and is best addressed at the Spark data sources API level. Thus, I think we should redirect this discussion to the Spark users mailing list and will close this ticket as out of scope.
