### ISSUE TITLE
Hadoop configuration "avro.mapred.ignore.inputs.without.extension" is ignored after upgrading to Spark 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by liancheng** [databricks/spark-avro#136]
In Spark 1.x, we use `HadoopRDD` and `AvroInputFormat` to read Avro files. In this case, Hadoop configuration "avro.mapred.ignore.inputs.without.extension" is checked in `AvroInputFormat.getSplits()` to ignore files whose paths don't end with ".avro". See [here](https://github.com/apache/avro/blob/da22ffcba82efa50aa384b3acdf26561085e14f6/lang/java/mapred/src/main/java/org/apache/avro/mapred/AvroInputFormat.java#L54-L55).

However, in Spark 2.0, `FileFormat` data sources shortcut Hadoop split generation, thus this configuration is no longer checked. This causes problems when ".avro" files are mixed with other files under a single directory. For example, spark-redshift may generate ".avro" files together with a "manifest.json" file when writing a Redshift table. Now this JSON file triggers a “Not an Avro data file” error.

This issue blocks https://github.com/databricks/spark-redshift/pull/221.

**Comment by rxin** [comment]
Maybe we should add a path filter as part of the API in FileFormat?

**Comment by liancheng** [comment]
@rxin A path filter interface is worth adding. But it only solves this specific problem. Handling this Avro Hadoop configuration is still necessary for spark-avro. Otherwise it would be a breaking behavior change for this data source.

One take away of this issue is that we need to pay attention to logics inside those original Hadoop style `getSplits()` methods when implementing corresponding `FileFormat` data sources.

**Comment by marmbrus** [comment]
+1 to adding a path filter interface.  There is also special cased code in parquet for file filtering (i.e. don't ignore _metadata files).

**Comment by liancheng** [comment]
Filed https://issues.apache.org/jira/browse/SPARK-16317 for a general `FileFormat` file filtering interface.

**Comment by JoshRosen** [comment]
It looks like this was fixed in #137.
