### ISSUE TITLE
pyspark offline installation using downloaded jars

### ISSUE THREAD

**Issue by jaketbouma** [databricks/spark-avro#138]
For the java-challenged, it's not straightforward to get this up and running in an offline environment by downloading the jars and putting them in the right place.  Could we consider adding instructions to README?  spark-csv was a similar challenge.

Using pyspark, via jupyter, I managed (led by [issue #65](https://github.com/databricks/spark-avro/issues/65#issuecomment-121958262)) to get it to read/write a file by adding:

`spark-avro_2.10-2.0.1.jar` and apache `avro-1.7.7.jar`

to `PYSPARK_SUBMIT_ARGS`  jars option like:

`PYSPARK_SUBMIT_ARGS="--jars avro-1.7.7.jar,spark-avro_2.10-2.0.1.jar"`

with the absolute paths of the jar files.  Are there any other jars missing that could cause problems down the road?

**Comment by JoshRosen** [comment]
When using Maven or SBT, transitive dependencies are automatically resolved for you. When downloading the JARs yourself you'll need to make sure to include all of the appropriate dependencies. Please consult either the published Maven POM or our SBT build file for a complete list of dependencies. Given that these may change, I don't want to redundantly replicate this list in our README, so I'm not sure that there's any concrete followup for us to take here. Hence, I'm going to close this issue.
