### ISSUE TITLE
Questions not really issues.

### ISSUE THREAD

**Issue by ziziermao** [databricks/spark-avro#141]
From avro's document, they say schema is 

> Avro data is always serialized with its schema. Files that store Avro data should always also include the schema for that data in the same file. Avro-based remote procedure call (RPC) systems must also guarantee that remote recipients of data have a copy of the schema used to write that data.

Why we don't need any avro schema when using spark-avro?

**Comment by liancheng** [comment]
Just as you mentioned:

> Avro data is always serialized with its schema. ...

That said, Avro files are self-describing, and we can read the Avro schema directly out of the files to be read.

**Comment by ziziermao** [comment]
Sorry, I think my question was not clear, the situation is when we write to avro, instead of reading from avro.
When we write to avro, I guess we write data to avro, dataframe rows could automatically be transfered to avro using .avro right? (it extract the schema from the data I guess?)

**Comment by liancheng** [comment]
When writing data through spark-avro, you are actually writing data within *DataFrames*, which are always self-describing and contain their own schema information in the form of a `StructType`. And we can convert a `StructType` into an Avro schema.

**Comment by naegelejd** [comment]
I'd like to piggyback on this question and ask: Is it currently possible to read AVRO files written via spark-avro (Spark's DataFrame interface) using only AVRO and Hadoop libraries? If so, do I need to use a specific AVRO reader?
