### ISSUE TITLE
Spark Avro(2.0.1) Reader needs higher spark driver memory on Yarn cluster mode?

### ISSUE THREAD

**Issue by jatinder85** [databricks/spark-avro#164]
Spark Avro reader with ~400 avro files in a directory fails unless I increase the spark driver memory? Can anybody explain why will that be or point to any resources?

**Comment by JoshRosen** [comment]
Not sure. The best way to make this actionable would be to capture a heap dump when the driver OOMs and figure out where the memory is going.

Absent that additional information, I'm not sure that this is super actionable, so I'm going to close this for now.
