### ISSUE TITLE
Document how to load avro files from multiple different directories at once

### ISSUE THREAD

**Issue by boosh** [databricks/spark-avro#17]
I've tried separating paths with commas (e.g. "s3n://mybucket/my/first/path/,s3n://mybucket/my/second/path/"), but can't find how to load multiple different directories of avro files into the same RDD. 

I got no response on the mailing list.

Please provide examples of loading multiple different directories into the same SchemaRDD in the docs. Thanks.

**Comment by vlyubin** [comment]
Unfortunately, this is not supported yet (we only support reading all avro files from some directory). However, you can try uniting your RDD's with ++:
```val combinedRDD = someSQLContext.avroFile("s3n://mybucket/f1") ++ someSQLContext.avroFile("s3n://mybucket/f2")
```

**Comment by boosh** [comment]
OK thanks I didn't know I could use ++ to join RDDs.

**Comment by boosh** [comment]
Actually, I get an error trying to create a temporary table using this:

EmrPoc.scala:23: value registerTempTable is not a member of org.apache.spark.rdd.RDD[org.apache.spark.sql.Row]
[error]     val data = combinedRDD.registerTempTable("data")

How can I create a temp table after adding RDDs together?

**Comment by vlyubin** [comment]
Ah, sorry, my bad. Apparently ++ (or union) takes another RDD and returns an RDD. `unionAll()`, on the other hand takes another SchemaRDD and returns a SchemaRDD. Since we need SchemaRDD to use registerTempTable, `unionAll()` should be used. I just tried the following code and it worked for me:

```val episodes1 = sqlContext.avroFile("../../src/test/resources/episodes.avro")
val episodes2 = sqlContext.avroFile("../../src/test/resources/episodes.avro")
val e = episodes1.unionAll(episodes2)
e.registerTempTable("episodes")
```

Let me know if this allows you to get a desired result.

**Comment by boosh** [comment]
Yes this works. Thanks a lot.
