### ISSUE TITLE
java.lang.AbstractMethodError: com.databricks.spark.avro.DefaultSource.createRelation

### ISSUE THREAD

**Issue by gaqzcb** [databricks/spark-avro#172]
Enviroment：

Scala2.10.4
Spark 1.5.1
databricks-avro 2.0.1

![spark-avro-error](https://cloud.githubusercontent.com/assets/16889930/18473675/d5c268fc-79f0-11e6-90f1-7a4b38526cf0.png)

**Comment by bit1129** [comment]
one thing to add，i am able to run in local mode，but hits the problem when running in yarn client mode

**Comment by gaqzcb** [comment]
@marmbrus @ksedgwic @davies @JoshRosen

**Comment by marmbrus** [comment]
`AbstractMethodError` always means that you are mixing up library versions. See the readme for which versions of the library and spark are compatible, and check your classpath to make sure you are actually using the versions you think you are.

**Comment by bit1129** [comment]
Thanks @marmbrus for the reply. I am using spark-avro 2.0.1 and using spark 1.5.1.  I rebuild the spark-avro code against spark 1.5.1, and then package the code with my sample test app in the same jar, when I submit the app using yarn-client,the same error still occurs
