### ISSUE TITLE
spark-avro 3.0 not partitioning based on hdfs blocks?

### ISSUE THREAD

**Issue by tgravescs** [databricks/spark-avro#179]
@JoshRosen 
Has something changed with spark-avro. When I ran with 1.0 and 2.0.1 versions in 1.6 I would get the number of tasks equal to number of hdfs blocks.  So for instance 600MB single avro file would get 5 tasks.  Now with 3.0 it uses one tasks to read the entire 600MB file, which is slow.

This is doing basic query like:
val  df = spark.read.format("com.databricks.spark.avro").load("file.avro");
df.filter(col("sendTime").equalTo(1450251840233226L)).map(r => r.getLong(1)).count()

**Comment by JoshRosen** [comment]
@tgravescs, I'm not sure. I'm more of a part-time contributor than a real maintainer of `spark-avro`. @clockfly and @liancheng, could you take a look since you're more familiar with the changes in 3.x?

**Comment by liangzhaozeng** [comment]
@clockfly  @liancheng @JoshRosen @tgravescs 
I read the source code, it seems to me only one reader is open for a file. And it is a very big performance issue. Do we have plan to fix it?

**Comment by tgravescs** [comment]
@clockfly @liancheng  any chance you guys can take a look at this?

**Comment by koertkuipers** [comment]
@liangzhaozeng where in source code do you see it opening only one reader for a file?
i see buildReader opens one reader for a PartitionedFile, but i assumed this means a single avro file gets split up

**Comment by koertkuipers** [comment]
oh never mind i see it now...
          val in = new FsInput(new Path(new URI(file.filePath)), conf)
its ignoring PartitionedFile.start and PartitionedFile.length etc.
