### ISSUE TITLE
Not able to read Avro Files using external Schema

### ISSUE THREAD

**Issue by guptam** [databricks/spark-avro#183]
I am using .option("avroSchema", schema.toString), but it is not using the external schema file, and uses the embedded schema only. 
I am using spark-avro_2.10, 2.0.1 on spark 1.6.0.

**Comment by JoshRosen** [comment]
This feature is only available in the current master branch of this library (which corresponds to the unreleased version 3.1.0) and is unavailable in version 2.0.1. See #160.
