### ISSUE TITLE
Wrong Scala type for Avro map type

### ISSUE THREAD

**Issue by mikaelstaldal** [databricks/spark-avro#186]
The Avro type `map` is currently mapped to Scala type `scala.collection.Map`. However, it would make more sense to map it to Scala type `scala.collection.immutable.Map` (a.k.a. `Predef.Map`).

Currently, mapping the DataFrame from spark-avro to a Dataset of a case class generated from Avro schema fails if the Avro map type is used since the generated case class uses `scala.collection.immutable.Map`.

You get an error message like this:

```
ERROR org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator - failed to compile: org.codehaus.commons.compiler.CompileException: File 'generated.java', Line 339, Column 69: No applicable constructor/method found for actual parameters "java.lang.String, java.lang.String, java.lang.String, double, java.lang.String, java.lang.String, int, scala.collection.Map, scala.collection.Map, long, long"; candidates are: "com.magine.telemetry.TelemetryEvent(java.lang.String, java.lang.String, java.lang.String, double, java.lang.String, java.lang.String, int, scala.collection.immutable.Map, scala.collection.immutable.Map, long, long)", "com.magine.telemetry.TelemetryEvent()"
```

The case class is generated with [Avrohugger](https://github.com/julianpeeters/avrohugger).

**Comment by JoshRosen** [comment]
This is a good point. I'd be happy to accept patches to fix this, but one concern of mine is that changing this might break users relying on the existing behavior. Is that the case? If so, can we add a feature-flag to fallback to the old behavior?

**Comment by mikaelstaldal** [comment]
After a closer look at the code of spark-avro, it seems like the problem is not here, it is in spark SQL catalyst:
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/CatalystTypeConverters.scala#L41

**Comment by JoshRosen** [comment]
Ah, interesting. Given that this seems like a general Spark issue, do you mind filing a JIRA against Apache Spark to discuss this?

**Comment by mikaelstaldal** [comment]
I found this Spark JIRA issue and made a comment on it: https://issues.apache.org/jira/browse/SPARK-14767

**Comment by JoshRosen** [comment]
Cool, thanks for tracking that down. In order to keep the open issue backlog tidy, I'm going to resolve this as 'not-a-spark-avro-issue' for now.
