### ISSUE TITLE
Where is the partition function?

### ISSUE THREAD

**Issue by qiaojialingithub** [databricks/spark-avro#187]
Hello.In features you list partitioning which allows developers to read partitioned data.But i don't find the partitioner's code in the   ##project.
I wonder how spark gets partitions based on external datasource's metadata.Thx.

**Comment by JoshRosen** [comment]
This question is better suited to the Spark developer mailing list.

**Comment by qiaojialingithub** [comment]
I have known how it works.Thank you!
