### ISSUE TITLE
NotSerializableException when calling `first()`

### ISSUE THREAD

**Issue by marmbrus** [databricks/spark-avro#2]
```
val person = sqlContext.avroFile("/tmp/person.avro")

When I try to call `first()` on it, I get "NotSerializableException" exceptions again:

person.first()

...
14/11/21 12:59:17 ERROR Executor: Exception in task 0.0 in stage 14.0 (TID 20)
java.io.NotSerializableException: org.apache.avro.generic.GenericData$Record
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
    at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1377)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1173)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
```

**Comment by vlyubin** [comment]
While it's impossible to actually try this without knowing what person.avro has in it (this isn't mentioned on the corresponding mailing list thread either), this problem most likely wouldn't occur anymore. This particular exception could have happened before if there was a nested record - we were not making recursive call to convert the nester record and instead were trying to write it as is, which would result in the exception above.

This has been fixed now, and we can successfully read files that have nested records and almost every avro datatype (except complex unions).
