### ISSUE TITLE
partition discovery

### ISSUE THREAD

**Issue by koertkuipers** [databricks/spark-avro#202]
does spark-avro support partition discovery?
i have a layout like:
```
/dir1
  /subrdir1
    part-00000.avro
    part-00001.avro
```
when i read from /dir1 i get:
```
Exception in thread "main" java.io.FileNotFoundException: No Avro files found. Hadoop option "avro.mapred.ignore.inputs.without.extension" is set to true. Do all input files have ".avro" extension?
```

i am using spark-avro 3.1.0 with spark 2.0.2

**Comment by marmbrus** [comment]
We only do partition discovery if the directories look like partitions (i.e. `/key=value/`).  In this case you could use globs `/dir1/*/*`.

**Comment by koertkuipers** [comment]
ah of course. i forgot about that. makes sense. thanks
