### ISSUE TITLE
Build fails, unresolved dependencies

### ISSUE THREAD

**Issue by mathstream** [databricks/spark-avro#207]
Hi,

I cloned the repo and used sbt/build, it fails as it cannot find these dependencies:

sbt.ResolveException: unresolved dependency: org.glassfish.hk2#hk2-locator;2.22.2: not found
unresolved dependency: javax.validation#validation-api;${javax.validation.version}: not found

I'm using OS X 10.12 (Sierra), and have no issues running Spark & Scala (they are already installed). Is this some additional dependency that I need to download and install?

Regards,
Alan

**Comment by vlyubin** [comment]
Just built fine for me on OS X... Any chance you just had connectivity issues?
