### ISSUE TITLE
Support for streamed writing

### ISSUE THREAD

**Issue by manugarri** [databricks/spark-avro#214]
With the new [structured streaming api](http://spark.apache.org/docs/latest/structured-streaming-programming-guide.html) released in Spark, the new api for writing a Stream is as follows. As an example, I am reading from kafka and writing to hdfs in avro format. 

```
kafkaStream = (
           spark
          .readStream
          .format("kafka")
          .option("kafka.bootstrap.servers", BROKER)
          .option("subscribe", INPUT_QUEUES)
          .load()
    )

# now we write the stream
    query = (
            kafkaStream
            .writeStream
           .format("com.databricks.spark.avro")
           .option("path", PATH)
           .option("checkpointLocation", "/tmp/")
           .start()
            )
    query.await

```
This works well if the `writeStream` format is `parquet` or `console` for example, but when you use the format `com.databricks.spark.avro` it breaks with the following error:

```
java.lang.UnsupportedOperationException: Data source com.databricks.spark.avro does not support streamed writing 
```

Are there any plans of supporting this new api?

**Comment by manugarri** [comment]
Any update on the project? Is it abandoned? It's been 2 months since i posted this.

**Comment by nightscape** [comment]
We'd also be interested in this. Is this as simple as adapting [this example stream sink](https://github.com/holdenk/spark-structured-streaming-ml/blob/master/src/main/scala/com/high-performance-spark-examples/structuredstreaming/CustomSink.scala) to write Avro?
If so, we can give it a try and create a PR.

**Comment by manugarri** [comment]
@nightscape  let me know how I can help

**Comment by aaron-aa** [comment]
We also need this feature,  we have lots of event data persist with avro. Is there any plan of supporting avro output format in structure streaming ?

**Comment by manugarri** [comment]
@aaron-aa  I dont think this project is maintained anymore.

**Comment by marmbrus** [comment]
Sorry for the delay here!  This library is not abandoned, and we just made the [4.0.0 release](https://github.com/databricks/spark-avro/releases/tag/v4.0.0).

With Spark 2.2.x and version 4.0.0 of this library, you can write out Avro data using structured streaming.  I tested using the following:

```scala
spark.readStream
  .format("rate")
  .load()
  .writeStream
  .format("com.databricks.spark.avro")
  .option("checkpointLocation", "/home/michael/avro/_checkpoint")
  .start("/home/michael/avro")
```

I'm going to close this ticket since this now works, but please reopen if you experience any issues.

**Comment by manugarri** [comment]
@marmbrus Great! Looking forward to test it :)

**Comment by hershs** [comment]
@marmbrus , Can I define output schema for the avro messages? I have different versions of schema in the kafka.
