### ISSUE TITLE
Support nested directory structure?

### ISSUE THREAD

**Issue by qiaojialin** [databricks/spark-avro#225]
I wonder whether spark supports nested directory for external data sources? 
Spark for parquet supports nested directory but when I put a directory path into the options, spark only gives me the FileStatue of files directly under the folder.
Thanks.

**Comment by koertkuipers** [comment]
it only supports nested directory structures of the key=value format, for parquet and avro.
so for example:
```
mydata/
  x=1/
    part-00000.avro
  x=2/
    part-00000.avro
```

**Comment by qiaojialin** [comment]
Thank you, I know how spark resolves path.

**Comment by smaley07** [comment]
Any update on this ?
