### ISSUE TITLE
spark.read.myfile() not allowed in spark-shell

### ISSUE THREAD

**Issue by qiaojialin** [databricks/spark-avro#233]
Hello, I'm doing the external data source of spark with our file format "tsfile".
I add a method to DataFrameReader
![2017-06-09 6 53 25](https://user-images.githubusercontent.com/7240743/26972662-4e81e68c-4d45-11e7-8eef-e99ff76fe861.png)

And it works fine in test.
![2017-06-09 6 54 17](https://user-images.githubusercontent.com/7240743/26972693-6e8b7600-4d45-11e7-8c81-6c0141b5e0a1.png)

But I can't use this way in spark-shell.
<img width="631" alt="2017-06-09 6 53 00" src="https://user-images.githubusercontent.com/7240743/26972717-854d940e-4d45-11e7-87af-a8467a007a4a.png">

Could any one help me? Thanks.

The repository is https://github.com/qiaojialin/tsfile-spark-connector

**Comment by sadikovi** [comment]
Try adding jar when starting spark-shell and importing implicits, e.g. `import cn.edu.thu.tsfile._`. This should work.

**Comment by qiaojialin** [comment]
Thank you, it works.
