### ISSUE TITLE
NullPointerException in Initializing HDFSInputStream

### ISSUE THREAD

**Issue by qiaojialin** [databricks/spark-avro#234]
In my own data source connector. I meet a NullPointerException in initializing HDFSInputStream.
<img width="936" alt="2017-06-14 3 00 51" src="https://user-images.githubusercontent.com/7240743/27119502-ae170e94-5112-11e7-9e99-8435483d94b7.png">

My connector works fine in local mode, both inferSchema and buildReader.
But when I run in cluster using `spark-shell --jars connector.jar --master spark://ip:7077`  
I can get schema of table but meet an error in buildReader().

The exception is from  the highlight line

![2017-06-14 3 07 39](https://user-images.githubusercontent.com/7240743/27119694-656f2acc-5113-11e7-82aa-e4312cb43923.png)

![2017-06-14 3 08 14](https://user-images.githubusercontent.com/7240743/27119696-668e7912-5113-11e7-8d88-9b9b3c5a6f6b.png)

Is it results from the deployment of my hadoop and spark? or a bug of my code? 
Thanks.

My connector repository is  https://github.com/qiaojialin/tsfile-spark-connector

**Comment by sadikovi** [comment]
Looks like a bug in `SerializableConfiguration` - hadoop configuration is null in closure. Plus, you do not use kryo in the methods anyway.

Try moving `SerializableConfiguration` into its own class and make code similar to this (should work):
```scala
import java.io.{ObjectInputStream, ObjectOutputStream}

import org.apache.hadoop.conf.Configuration

/**
 * Serializable hadoop configuration. Clone of `org.apache.spark.util.SerializableConfiguration`,
 * since it cannot be reused outside `spark` package.
 */
class SerializableConfiguration(@transient var value: Configuration) extends Serializable {
  private def writeObject(out: ObjectOutputStream): Unit = {
    out.defaultWriteObject()
    value.write(out)
  }

  private def readObject(in: ObjectInputStream): Unit = {
    value = new Configuration(false)
    value.readFields(in)
  }
}
```

**Comment by qiaojialin** [comment]
I moved this class in to my DefaultSource to replace the old and it works. Thank you brother!
