### ISSUE TITLE
NPE in outputWriterFactory.newInstance

### ISSUE THREAD

**Issue by qiaojialin** [databricks/spark-avro#237]
In my own data source I encountered a NullPointerException in outputWriterFactory.newInstance() in WriterContainer.scala

The test is good in spark local mode
![2017-06-26 5 59 18](https://user-images.githubusercontent.com/7240743/27534329-338a06dc-5a99-11e7-92dc-6b26f60cdb64.png)

But when I run command in spark-shell I got this error
![2017-06-26 5 50 12](https://user-images.githubusercontent.com/7240743/27534264-fc325cfc-5a98-11e7-968d-4d114289d479.png)

Looks like spark can't get my WriterFactory. Why this happen?

I have already override the prepareWrite
![2017-06-26 6 07 30](https://user-images.githubusercontent.com/7240743/27534659-64aba1f2-5a9a-11e7-8091-966350f2aada.png)

Thanks.

My connector repository is https://github.com/qiaojialin/tsfile-spark-connector

**Comment by sadikovi** [comment]
Difficult to say without debugging the code. I do not have much experi nice with write part of data sources. 

I suggest you make 'options' property as 'val' in your 'TsFileWriterFactory' - it currently does not have prefix on it. This might be the problem.

**Comment by qiaojialin** [comment]
Thank you! It's no need to add val in parameters. 

It's turned out to be the environment problem of my spark cluster, I put a jar file in /spark/jars many days ago, when I using --jars to add the connector it will be replaced by the jar file in /spark/jars. Then spark can not find my WriteFactory.
