### ISSUE TITLE
Make it possible to specify partitons num while reading

### ISSUE THREAD

**Issue by timyitong** [databricks/spark-avro#26]
Currently the AvroRelation is using defaultMinPartitions of SparkContext while reading avro files. Could we consider adding an option to let users specify partitions number? That would make it possible to load data directly into a certain number of partitions instead of using a repartition operation when needed.

**Comment by vlyubin** [comment]
@timyitong Would you like to implement this?

**Comment by timyitong** [comment]
@vlyubin: sure, I can implement this. I actually have some hacky stuff going on.

**Comment by timyitong** [comment]
Sent pull request: #28
