### ISSUE TITLE
Spark 2.3 support

### ISSUE THREAD

**Issue by functicons** [databricks/spark-avro#294]
Spark 2.3 has been released in Q1 2018. Does spark-avro 4.0 support it? or is there any plan to support it?

**Comment by functicons** [comment]
It would be nice if we can update REAME to give the status of Spark 2.3 support.

**Comment by rondefreitas** [comment]
I run spark-avro 4.0 on Spark 2.3 regularly. No new issues that I didn't already encounter on 2.2

**Comment by OneCricketeer** [comment]
Probably should close in favor of #296
