### ISSUE TITLE
Will use KryoSerializer work in spark-avro?

### ISSUE THREAD

**Issue by java8964** [databricks/spark-avro#30]
Hi, in the SparkSQL, if I loaded my AVRO files and register them in tables, if I setup "spark.serializer" to "org.apache.spark.serializer.KryoSerializer", will it be honored by SparkSQL and SparkAvro? The reason is that currently I saw the gc time took more than 50% time, but even I enable the "kryoserializer", I didn't see any improvement. My question is that if the Spark-AVRO supports "KryoSerializer" internal? Thanks

**Comment by vlyubin** [comment]
It should ...

**Comment by vlyubin** [comment]
Whichever serializer is used by spark, should also be used by spark-avro. I'll close the issue now, but if you find out that it's not the case, please let us know and we'll investigate.

Thanks!
