### ISSUE TITLE
Be permissive when reading avro files with inconsistent schema

### ISSUE THREAD

**Issue by falaki** [databricks/spark-avro#31]
If there are multiple files in a directory and some of them have additional records, do not throw exception as long as those fields are not accessed. Ideally show a warning when loading. 

On a related note this can be controlled with a flag in the options.

**Comment by rxin** [comment]
This affects https://github.com/databricks/spark-avro/issues/49 also.

**Comment by nlande** [comment]
Any workarounds? We have an evolving but backwards compatable avro schema and this is a blocker for us.

**Comment by FRosner** [comment]
I would be happy to have this as I also ran into the same issue as #49. Anyone planning to pick it up?

**Comment by FRosner** [comment]
@JoshRosen can you give an indication on whether someone is going to pick it up? If it is required I can also invest some time and see if I can fix it. 

If someone already has some indications about the piece of code that has to be changed it is much appreciated.

**Comment by FRosner** [comment]
@nlande did you find a workaround so far? My workaround was to load every file individually. However, I ran into huge performance problems with several thousands of avro files because the DAG got pretty big... When trying to show it in the Spark UI, the UI even ran out of memory.

**Comment by Gauravshah** [comment]
should be solvable by specifying a schema that is a union in itself. this pull request solves that https://github.com/databricks/spark-avro/pull/95

**Comment by adilakhter** [comment]
Hi guys, is there any plan to fix this issue? We are currently facing a similar issue.

**Comment by Gauravshah** [comment]
should be able to do this by specifying a schema while loading files https://github.com/databricks/spark-avro/commit/b078cca6d7b7b758a75eaec6ab1dfc3fafc1c368

**Comment by JoshRosen** [comment]
I think @Gauravshah is right: this should be addressed by the "custom read schema" support that is added in the forthcoming 3.1.0 release, so I'm going to go ahead and tentatively mark this as fixed.
