### ISSUE TITLE
SchemaConverter is private, can we expose an API for it?

### ISSUE THREAD

**Issue by timyitong** [databricks/spark-avro#34]
The use case is that sometimes a user might want to store an RDD with a specific Avro schema, if there is a converter available, it will be fairly easy to do something like:
```
val schema = new Schema.Parser().load('bla') // Avro Schema class
val structType = new SchemaConverter().toSql(schema)
val rddWithRightSchema = sqlContext.applySchema(rdd, structType)
rddWithRightSchema.saveAsAvroFile("/foo/bar")
```

**Comment by TDDFT** [comment]
+1

**Comment by vlyubin** [comment]
Sounds reasonable, we'll implement this soon.

**Comment by marmbrus** [comment]
I'm not sure exactly what the use case being proposed here is.  Today, you can load avro data, and get the schema from the resulting dataframe by calling `df.schema`.

I'm going to close this, but please reopen with more details about what you are trying to accomplish if I'm missing something.

**Comment by timyitong** [comment]
@marmbrus , the use case is on the writing side inside of the reading side. For example, if we have generated an arbitrary RDD (not a DateFrame), and want to finally store it as an Avro file. There are two options: 1. using AvroWriter, outputformat directly; or 2. cast the RDD into a dataframe and use #saveAsAvroFile method.

In the latter way, user needs to create a copy of the structType which serves as the schema for the dataframe. However, since our final target is Avro, what we have is an Avro schema. So the choices are either we hard code the StructType creation logics or we call the SchemaConverter APIs and automatically figure out the DateFrame StructType from an Avro schema.

This is based upon my understanding around spark-avro 1.0, Spark 1.2. Have things changed in the latest version that we no longer need to create StructType from Avro schema anymore in this case?

**Comment by marmbrus** [comment]
In general I'd suggest that most people use [the simpler methods for create DataFrames from RDDs that don't require you to manually specify the schema](https://spark.apache.org/docs/latest/sql-programming-guide.html#inferring-the-schema-using-reflection).  However, I guess opening two small static functions `Schema => StructType` and `StructType => Schema` would be reasonable if you want to make a PR.

**Comment by adamjk** [comment]
+1 It would be nice to have this in Java where you don't want to generate schema objects and are using GenericRecords for writing in Spark.

**Comment by hkothari** [comment]
When would this change be available in a release? I can't seem to find a release schedule for this package but I know of a few places that could benefit from reusing the SchemaConverters code.

**Comment by timyitong** [comment]
I think the commit is merged:
https://github.com/databricks/spark-avro/commits/master

2016-02-05 14:50 GMT-08:00 hkothari <notifications@github.com>:

**Comment by hkothari** [comment]
Apologies for the confusion, I'm asking when the next spark-avro release will be tagged and pushed to maven central, with this commit.

**Comment by abilng** [comment]
@hkothari Which 2.x version has these changes?
