### ISSUE TITLE
Avro Spark is incompatible with Spark 1.3.0

### ISSUE THREAD

**Issue by deepujain** [databricks/spark-avro#36]
Can we expect a release compatible with 1.3.0 ?

**Comment by vlyubin** [comment]
As of now, the PR for 1.3 was merged, so if it's urgent, you can build the package from source. It should be published by the end of the week.

**Comment by deepujain** [comment]
What branch is it in ? I did checkout master and modified build.sbt to use 1.3.0 and it failed.

**Comment by vlyubin** [comment]
Um, master has the code for 1.3. It was only merged today, so if you checked it out before, be sure to pull the updated version.

**Comment by vlyubin** [comment]
`1.0.0` version was released for Spark 1.3 (see README).
