### ISSUE TITLE
Where is the build for Spark 1.2.x, or 0.2.0 branch?

### ISSUE THREAD

**Issue by java8964** [databricks/spark-avro#44]
Hi, our production environment will deploy Spark 1.2.x, and from the README, it looks like spark-avro also support Spark 1.2.x. But I cannot either find a release for Spark 1.2.x, nor the branch for 0.2.0, as claimed in the README for Spark 1.2.x? Can someone tell me if there is  bin release for Spark 1.2.0, or where is the source code if I have to build it myself? Thanks

[spark-avro]$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/update_artifacts

**Comment by vlyubin** [comment]
You can get the 0.2.0 version from maven (http://search.maven.org/#artifactdetails%7Ccom.databricks%7Cspark-avro_2.10%7C0.2.0%7Cjar).
There isn't a separate branch for it (we should probably make it though), but if you need source code, then commit https://github.com/databricks/spark-avro/tree/a788c9fce51b0ec1bb4ce88dc65c1d55aaa675b8 is the last one for the 1.2 version (we upgraded to 1.3 afterwards). You can browse files here: https://github.com/databricks/spark-avro/tree/a788c9fce51b0ec1bb4ce88dc65c1d55aaa675b8

**Comment by brianmartin** [comment]
Yes, please add tag/branch for releases. This is quite confusing.

**Comment by marmbrus** [comment]
Docs have been updated. Sorry for the confusing.  Closing.
