### ISSUE TITLE
Support custom converters

### ISSUE THREAD

**Issue by sixers** [databricks/spark-avro#53]
Avro types are quite limited, whereas Spark support wider set of types including DecimalType and DateType. Some people (including me) work around that by using nested records, e.g: 

```
{
            "name" : "some_date_field",
            "type" : [ "null", {
              "type" : "record",
              "name" : "date",
              "namespace" : "avro",
              "fields" : [ {
                "name" : "value",
                "type" : [ "string", "null" ]
              } ]
            } ],
            "default" : null
          }
```

It would be nice to register a converter which converts all fields with type "avro.date" to DateType() on read. And vice versa, DateType() to this kind of nested record on save.

What to you think?

**Comment by marmbrus** [comment]
This seems like a reasonable solution, but doesn't sound avro specific to me.  Could you do what you want by using UDFs and extending dataframe:

```scala
import org.apache.spark.sql._
import org.apache.spark.sql.types._
import org.apache.spark.sql.functions._
​
​
case class EncodedType(baseType: String, value: String)
​
val encodeDecimal = udf((d: BigDecimal) => EncodedType("decimal", d.toString))
​
implicit class DataConverter(df: org.apache.spark.sql.DataFrame) {
  def encodeDecimals() = {
    val fields = df.schema.fields.filter(_.dataType == DecimalType())
    fields.foldLeft(df){ (oldDF, field) =>
      oldDF.withColumn(field.name, encodeDecimal(oldDF(field.name)))
    }
  }

  def decodeDecimals = ...
}

val df = Seq(("hello", BigDecimal(1))).toDF("a", "b")
df: org.apache.spark.sql.DataFrame = [a: string, b: decimal(10,0)]

df.encodeDecimals
res8: org.apache.spark.sql.DataFrame = [a: string, b: struct<baseType:string,value:string>]
```

**Comment by JoshRosen** [comment]
I agree with Michael; I think we need to hear an argument that this can only be accomplished or best accomplished in a way that's specific to this library before we want to add a new feature for this. Therefore, I'm going to close this as `wontfix` for now.
