### ISSUE TITLE
Support for compression

### ISSUE THREAD

**Issue by ankurmitujjain** [databricks/spark-avro#55]
Hi I was looking to read and write my dataset in avro format using snappy compression.
Does this is supported? any examples or pointers will be great help.

Thanks

**Comment by vlyubin** [comment]
Hey Ankur,

We don't really have anything specific for this, but it should be quite simple to accomplish. If you want to save dataframe `df` by calling `AvroSaver.save`, before you do so just make the two calls below:

```
df.sqlContext.sparkContext.hadoopConfiguration.set("mapred.output.compress", "true")
df.sqlContext.sparkContext.hadoopConfiguration.set("avro.output.codec", "deflate")
```

That way the compression that you specified should be used. I just tried this, and it worked for me. Alternatively, you can change

```
val jobConf = new JobConf(dataFrame.sqlContext.sparkContext.hadoopConfiguration)
```

to

```
val jobConf = new JobConf(dataFrame.sqlContext.sparkContext.hadoopConfiguration)
jobConf.set("mapred.output.compress", "true")
jobConf.set("avro.output.codec", "snappy")
```

inside `AvroSaver.save` method if you want to change the source itself.

As for reading, I don't think there should be any issues. I hope this helps.

**Comment by ankurmitujjain** [comment]
Thanks Volodymyr
