### ISSUE TITLE
Extend HadoopFsRelation?

### ISSUE THREAD

**Issue by JDrit** [databricks/spark-avro#58]
Can there be an Avro relation that extends [HadoopFSRelation](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala#L368), similar to how there are two Parquet relations [ParquetRelation2](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/parquet/newParquet.scala#L90) and [ParquetRelation](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/parquet/ParquetRelation.scala#L49). This would allow it to take advantage of all the work done by the base HadoopFsRelation. This would require a dependency on spark-1.4 though.

**Comment by marmbrus** [comment]
I would like to do this, but making a release with this version would need to block on us making that API public.  That said, this is something I want to do, and even a prototype using the private API would be valuable to let us know if we are missing anything that is required on the Spark side.

Related, this might fix: #40

**Comment by JDrit** [comment]
I submitted a PR that uses the new HadoopFsRelation and DataFrameReader. Is this what you are looking for? I tried to match the pattern used by the current implementation of spark-avro and [ParquetRelation2](https://github.com/JDrit/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/parquet/newParquet.scala#L90).

https://github.com/databricks/spark-avro/pull/59

**Comment by marmbrus** [comment]
Sounds great.  I will try and give a review next week!

**Comment by JoshRosen** [comment]
Closing this as fixed since #59 was merged.
