### ISSUE TITLE
2.0.0 artifact is not in any public maven repo

### ISSUE THREAD

**Issue by kcsham** [databricks/spark-avro#85]
I'm not able to resolve com.databricks#spark-avro_2.10;2.0.0 in any well-known repository. I see 1.0.0 is in central maven repo. Could we have 2.0.0 deployed there? 

Even after I've built from source 2.0.0 and publish-local, i'm unable to run spark-shell successfully as noted in README.md:

    spark-shell --packages com.databricks:spark-avro_2.10:2.0.0

**Comment by JoshRosen** [comment]
I believe that we're still in the process of publishing `spark-avro` to spark-packages.org and Maven Central; I expect that we'll finish this process today.

In the meantime, the 2.0.0 release artifacts are staged on Bintray: https://bintray.com/databricks/maven/spark-avro/2.0.0/view

**Comment by kcsham** [comment]
Nice. Thanks. shell is up with:

    $ spark-shell --packages com.databricks:spark-avro_2.10:2.0.0 --repositories "http://dl.bintray.com/databricks/maven"

**Comment by marmbrus** [comment]
Yeah, to confirm, we are working on this.

**Comment by JoshRosen** [comment]
There was a problem with the 2.0.0 POM which prevented publication to Maven Central. We just published version 2.0.1 to Maven Central, though.

**Comment by JoshRosen** [comment]
This has been fixed. 2.0.1 is in Maven Central.
