### ISSUE TITLE
Expose the GenericRecord to Row conversion

### ISSUE THREAD

**Issue by fvlankvelt** [databricks/spark-avro#88]
The AvroRelation class contains some very useful code to convert data from a GenericRecord to a Row representation.  This functionality is purely about Spark SQL / Avro interoperability.  However, it is currently tied to hdfs (the buildScan method in AvroRelation).  It would be most convenient if this code were extracted so that it could also be used with other persistence engines.

Concretely, I'm attempting to read Avro records from Kafka.

**Comment by JoshRosen** [comment]
This seems related to #34?

**Comment by fvlankvelt** [comment]
That issue seems to more about writing avro files with a specific schema.  This one is about reading avro records from a non-hdfs storage engine.

The issues are related in that both wish to leverage the spark-avro code by means of a clean api.

I'll try to come up with a PR.

**Comment by JoshRosen** [comment]
Per my comment at https://github.com/databricks/spark-avro/pull/89#issuecomment-263147247, I think the right approach here is to expose an AvroSchema to `ExpressionEncoder[GenericRow]` interface, as described in #169. Thus, I'm going to close this as "won't fix" but will gladly accept help on #169.
