### ISSUE TITLE
Force output to single avro-file

### ISSUE THREAD

**Issue by honzasterba** [databricks/spark-avro#99]
When running with smaller dataset the writer generates hundreds of empty .avro -part files. It would be nice if there was an option forcing the writer to write data into a single result .avro or at least some reasonable number of output files.

**Comment by boosh** [comment]
Try calling `coalesce(1)` on your RDD before writing it. The entire result must fit in RAM though.

**Comment by JoshRosen** [comment]
Yep, the right solution here is to either use `coalesce()` to reduce the number of partitions or to perform some sort of post-processing step to combine the files. Both are out of scope w.r.t this library itself, though, so I'm going to close this issue.
